apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        api: external        
    spec:
      containers:
      - image: docker.io/ifakaowoh/udagram-frontend
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "2048Mi"
            cpu: "600m"
          limits:
            memory: "2048Mi"
            cpu: "600m"                
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  selector:
    app: frontend