name: project ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push feed
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./udagram-api-feed/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/udagram-api-feed:v1
          
      -
        name: Build and push user
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./udagram-api-user/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/udagram-api-user:v1
          
      -
        name: Build and push front-end
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./udagram-frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/udagram-frontend:v1
          
      -
        name: Build and push reverse-proxy
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./udagram-reverseproxy/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/reverseproxy:v1
