name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and deploy the Docker image
      run: |
        docker build -t udagram-api-feed ./udagram-api-feed
        docker tag udagram-api-feed ifakaowoh/udagram-api-feed
        docker build -t udagram-api-user ./udagram-api-user
        docker tag udagram-api-user ifakaowoh/udagram-api-user
        docker build -t udagram-frontend ./udagram-frontend
        docker tag udagram-frontend ifakaowoh/udagram-frontend:v4
        docker build -t reverseproxy ./udagram-reverseproxy
        docker tag reverseproxy ifakaowoh/reverseproxy
        echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push ifakaowoh/udagram-api-feed
        docker push ifakaowoh/udagram-api-user
        docker push ifakaowoh/udagram-frontend:v4
        docker push ifakaowoh/reverseproxy
